### ISSUE TITLE
inference.py  problem

### ISSUE THREAD

**Issue by SoberDanz** [sahilg06/EmoGen#22]
I was running the inference.py and I got this error

Traceback (most recent call last):
  File "/sharefiles/zhaodan/projects/EmoGen-master/inference.py", line 298, in <module>
    main()
  File "/sharefiles/zhaodan/projects/EmoGen-master/inference.py", line 233, in main
    mel = audio.melspectrogram(wav)
  File "/sharefiles/zhaodan/projects/EmoGen-master/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/sharefiles/zhaodan/projects/EmoGen-master/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/sharefiles/zhaodan/projects/EmoGen-master/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were give

Thanks and regards

**Comment by zk19971101** [comment]
this problem is caused by the incompatibale version of librosa, try
pip uninstall librosa
pip install librosa==0.7.1
